### PR TITLE
Deleted unnecessary tomcat7-maven-plugin from pom.xml.

### PR DESCRIPTION
**Pull request by dmytro-verner**

### CODE REVIEW

**Comment by yaroslav-orel** [comment]
How would we deploy without this plugin?

**Comment by dmytro-verner** [comment]
There is no problem deploying it to Tomcat - performed the same steps and had no trouble. I think when we'll really need this we'd add this.

**Comment by yaroslav-orel** [comment]
Could you please specify the steps?

**Comment by dmytro-verner** [comment]
In maven: Clean -> Install
Run tomcat from configuration in IntelliJ

The war file gets deployed to tomcat without any issues.

**Comment by ghost** [comment]
It's nice that Ultimate Idea has built-in tomcat support but our solution
shouldn't rely on this feature. Maven plugin is obligatory to be able to
deploy application using bare commandline. And this is the way it's going
to be handled by CI btw.

**Comment by yaroslav-orel** [comment]
Let's leave it as it is for now.

**Pull request closed without merging**
